apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ticketing-micro-tls
  namespace: default
spec:
  secretName: ticketing-micro-tls
  dnsNames:
    - ticketing-micro.shop
    - www.ticketing-micro.shop
    - grafana.ticketing-micro.shop
    - prometheus.ticketing-micro.shop
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
