apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 10s

    scrape_configs:
      - job_name: 'auth-service'
        static_configs:
          - targets: ['auth-srv:3000']
    
      - job_name: 'tickets-service'
        static_configs:
          - targets: ['tickets-srv:3000']
    
      - job_name: 'orders-service'
        static_configs:
          - targets: ['orders-srv:3000']
    
      - job_name: 'payments-service'
        static_configs:
          - targets: ['payments-srv:3000']
    
      - job_name: 'expiration-service'
        static_configs:
          - targets: ['expiration-srv:3000']

